import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';


@Component({
  selector: 'app-main',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './main.component.html',
  styleUrl: './main.component.css'
})
export class MainComponent {
  quadres =[{
    "id": 3752,
    "api_model": "artworks",
    "api_link": "https://api.artic.edu/api/v1/artworks/3752",
    "is_boosted": false,
    "title": "The Madonna of the Rosary",
    "alt_titles": null,
    "thumbnail": {
      "lqip": "data:image/gif;base64,R0lGODlhAwAFAPMAAIqKd4+Pe5WVgJWUgZaVgZaXgpiYhJmZhJqahpubh52diaOijaink6qqlAAAAAAAACH5BAAAAAAALAAAAAADAAUAAAQLMAUlziiIKGDaYhEAOw==",
      "width": 2218,
      "height": 3258,
      "alt_text": "A work made of engraving on ivory laid paper."
    },
    "main_reference_number": "1956.836",
    "has_not_been_viewed_much": false,
    "boost_rank": null,
    "date_start": 1475,
    "date_end": 1485,
    "date_display": "c. 1480",
    "date_qualifier_title": "",
    "date_qualifier_id": null,
    "artist_display": "Israhel van Meckenem the Younger\nGerman, c. 1440/45-1503",
    "place_of_origin": "Germany",
    "description": null,
    "short_description": null,
    "dimensions": "Sheet: 27.1 \u00d7 18.5 cm (10 11/16 \u00d7 7 5/16 in.)",
    "dimensions_detail": [
      {
        "depth": null,
        "width": 18,
        "height": 27,
        "diameter": null,
        "clarification": "Sheet"
      }
    ],
    "medium_display": "Engraving on ivory laid paper",
    "inscriptions": null,
    "credit_line": "Bequest of Mrs. Potter Palmer, Jr.",
    "catalogue_display": "<p>Lehrs IX.199</p><p>Bartsch VI.221.48</p><p>Geisberg 182</p><p>Hollstein XXIV.199</p>",
    "publication_history": null,
    "exhibition_history": null,
    "provenance_text": null,
    "edition": null,
    "publishing_verification_level": "Web Basic",
    "internal_department_id": 3,
    "fiscal_year": null,
    "fiscal_year_deaccession": null,
    "is_public_domain": true,
    "is_zoomable": true,
    "max_zoom_window_size": -1,
    "copyright_notice": null,
    "has_multimedia_resources": false,
    "has_educational_resources": false,
    "has_advanced_imaging": false,
    "colorfulness": 9.2077,
    "color": {
      "h": 57,
      "l": 53,
      "s": 8,
      "percentage": 0.08786605265830741,
      "population": 917
    },
    "latitude": null,
    "longitude": null,
    "latlon": null,
    "is_on_view": false,
    "on_loan_display": "<p>On loan to Chazen Museum of Art in Madison for <i>Art of Enterprise: Israhel van Meckenem's 15th-Century Print Workshop</i></p>",
    "gallery_title": null,
    "gallery_id": null,
    "nomisma_id": null,
    "artwork_type_title": "Print",
    "artwork_type_id": 18,
    "department_title": "Prints and Drawings",
    "department_id": "PC-13",
    "artist_id": 37116,
    "artist_title": "Israhel van Meckenem, the younger",
    "alt_artist_ids": [],
    "artist_ids": [37116],
    "artist_titles": ["Israhel van Meckenem, the younger"],
    "category_ids": ["PC-13"],
    "category_titles": ["Prints and Drawings"],
    "term_titles": [
      "engraving",
      "paper (fiber product)",
      "print",
      "prints and drawing",
      "ink"
    ],
    "style_id": null,
    "style_title": null,
    "alt_style_ids": [],
    "style_ids": [],
    "style_titles": [],
    "classification_id": "TM-12",
    "classification_title": "engraving",
    "alt_classification_ids": ["TM-17", "TM-4"],
    "classification_ids": ["TM-12", "TM-17", "TM-4"],
    "classification_titles": ["engraving", "print", "prints and drawing"],
    "subject_id": null,
    "alt_subject_ids": [],
    "subject_ids": [],
    "subject_titles": [],
    "material_id": "TM-2982",
    "alt_material_ids": ["TM-2398"],
    "material_ids": ["TM-2982", "TM-2398"],
    "material_titles": ["paper (fiber product)", "ink"],
    "technique_id": null,
    "alt_technique_ids": [],
    "technique_ids": [],
    "technique_titles": [],
    "theme_titles": [],
    "image_id": "d0979087-dc1b-f259-a23f-169cdced27ee",
    "alt_image_ids": [],
    "document_ids": [],
    "sound_ids": [],
    "video_ids": [],
    "text_ids": [],
    "section_ids": [],
    "section_titles": [],
    "site_ids": [],
    "suggest_autocomplete_all": [
      { "input": ["1956.836"], "contexts": { "groupings": ["accession"] } },
      {
        "input": ["The Madonna of the Rosary"],
        "weight": 457,
        "contexts": { "groupings": ["title"] }
      }
    ],
    "source_updated_at": "2024-01-11T00:30:00-06:00",
    "updated_at": "2024-01-11T00:31:50-06:00",
    "timestamp": "2024-01-11T01:46:26-06:00"
  },
  {
    "id": 6010,
    "api_model": "artworks",
    "api_link": "https://api.artic.edu/api/v1/artworks/6010",
    "is_boosted": false,
    "title": "Number 19",
    "alt_titles": null,
    "thumbnail": {
      "lqip": "data:image/gif;base64,R0lGODlhAwAFAPMAAKlyV6pyWqt2Xad9W654XYx+d6qMUqyRV5OCdqeAaa+DbLWIaLeLcLKKd7ePgAAAACH5BAAAAAAALAAAAAADAAUAAAQLUASAFClptHUcMxEAOw==",
      "width": 16610,
      "height": 10836,
      "alt_text": "Blurry rectangles of yellow, gray, and black float against background of orange."
    },
    "main_reference_number": "1957.308",
    "has_not_been_viewed_much": false,
    "boost_rank": null,
    "date_start": 1949,
    "date_end": 1949,
    "date_display": "1949",
    "date_qualifier_title": "",
    "date_qualifier_id": null,
    "artist_display": "Mark Rothko (Marcus Rothkowitz)\nAmerican, born Russia (Latvia), 1903\u20131970",
    "place_of_origin": "United States",
    "description": "<p>Like many of the New York School painters of the 1940s, Mark Rothko was largely influenced by Surrealism, creating allegorical abstractions depicting biomorphic and mythological forms. By 1947 he abandoned representational imagery entirely and began working with color, light, and space. <em>Number 19</em> follows the characteristic format of his multiform paintings, in which loosely defined organic shapes hover over a thinly brushed background. Whereas color once assumed a supporting role in his compositions, by this period, color had become a defining force, thus marking the transition from Rothko\u2019s early work to his mature, color-field paintings.</p>\n",
    "short_description": null,
    "dimensions": "172.8 \u00d7 101.8 cm (68 \u00d7 40 1/8 in.)",
    "dimensions_detail": [
      {
        "depth": null,
        "width": 101,
        "height": 172,
        "diameter": null,
        "clarification": null
      }
    ],
    "medium_display": "Oil on canvas",
    "inscriptions": "Not inscribed on recto; inscribed: verso: \"Mark Rothko / 1949\" (lower left in orange-red paint); \"Top\" (on upper strainer member in orange-red paint)",
    "credit_line": "Anonymous gift",
    "catalogue_display": "<p>Anfam</p>",
    "publication_history": "Robert Goldwater, \u201cReflections on the Rothko Exhibition,\u201d \u201cArts\u201d 35, 6 (March 1961), p. 44 (ill.), as \u201cNo. 19, 1948.\u201d\n\nPeter Selz, \u201cMark Rothko,\u201d \u201cL\u2019Oeil\u201d 76 (April 1961), p. 39 (ill.), as \u201cNumber 19, 1948.\u201d\n\nT. Elder Dickson, \u201c\u2018Pure Art\u2019: Past Present and Future,\u201d \u201cThe Studio\u201d 162, 820 (August 1961), p. 45 (ill.), as \u201cNo. 19, 1948.\u201d\n\n\u201cPaintings in the Art Institute of Chicago\u201d (Art Institute of Chicago, 1961), p. 405.\n\nJohn Ashbery, \u201cParis Notes,\u201d \u201cArt International\u201d 7, 2 (February 25, 1963), p. 73 (inverted ill.), as \u201cNumber 19, 1948.\u201d\n\nRobert T. Buck, Jr. et al., \u201cSam Francis: Paintings 1947\u20131972,\u201d exh. cat. (Albright-Knox Art Gallery, 1972), p. 16 (ill.), as \u201cNo. 19, 1948.\u201d\n\nElizabeth Till, \u201cMark Rothko at the Guggenheim,\u201d \u201cNorthwest: The Sunday Oregonian Magazine\u201d (December 17, 1978), p. 11 (inverted ill.). \n\nDiane Waldman et al., \u201cMark Rothko, 1903\u20131970: A Retrospective,\u201d exh. cat. (Solomon R. Guggenheim Museum/Harry N. Abrams, 1978), pp. 56, 273, cat. 88 (color ill.). \n\nHugh Adams, \u201cModern Painting\u201d (Phaidon, 1979), p. 57 (color ill.), as \u201cPainting, 1953\u20134.\u201d\n\nNobuyuki Hiromoto, \u201cMark Rothko,\u201d Contemporary Great Masters 4 (Kodansha, 1993), pl. 13 (color ill.).\n\nJames N. Wood and Teri J. Edelstein, \u201cThe Art Institute of Chicago: Twentieth-Century Painting and Sculpture\u201d (Hudson Hills Press, 1996), p. 97 (color ill.).\n\nDavid Anfam, \"Mark Rothko, The Works on Canvas: A Catalogue Raisonn\u00e9\" (National Gallery of Art/Yale University Press, 1998), pp. 61, 69, fig. 65 (photo), cat. 403 (color ill.).\n\nGlenn Phillips and Thomas Crow, eds., \u201cSeeing Rothko\u201d (Getty Research Institute, 2005), p. 33, pl. 16 (color ill.).\n\nSuzanne Pag\u00e9, Rothko: Every Picture Tells a Story, exh. cat. (Paris: Citadelles & Mazemod, 2023), 77 (color ill.) 300.",
    "exhibition_history": "New York, Whitney Museum of American Art, \u201cAnnual Exhibition of Contemporary American Painting,\u201d December 16, 1949\u2013February 5, 1950, cat. 117.\n\nUrbana, College of Fine and Applied Arts, University of Illinois, \u201cExhibition of Contemporary American Painting,\u201d March 4\u2013April 15, 1951, p. 214, cat. 114, pl. 35 (ill.).\n\nNew York, Museum of Modern Art, \u201cMark Rothko,\u201d January 18\u2013March 12, 1961, cat. by Peter Selz, pp. 19 (ill.), 43, as \u201cNo. 19, 1948.\u201d\n\nBirmingham Museum of Art, \u201cTenth Anniversary Exhibition,\u201d April 30\u2013May 31, 1961, no cat.\n\nNagaoka, Japan, Niigata Prefectural Museum of Modern Art, \u201cMasterworks of Modern Art from the Art Institute of Chicago,\u201d April 20\u2013May 29, 1994; traveled to Nagoya, Aichi Prefectural Museum of Art, June 10\u2013July 24, 1994, and Yokohama Museum of Art, August 6\u2013September 25, 1994, cat. 65 (color ill.)\n\nWashington, D. C., National Gallery of Art, \u201cMark Rothko,\u201d May 3\u2013August 16, 1998, cat. by Jeffrey Weiss et al.; traveled to New York, Whitney Museum of American Art, September 10\u2013November 29, 1998, and Mus\u00e9e d\u2019Art Moderne de la Ville de Paris, January 8\u2013April 18, 1999, p. 342, cat. 39 (color ill.); French cat., cat. 21 (color ill.).\n\nParis, Fondation Louis Vuitton, Mark Rothko, Oct. 18, 2023\u2013Apr. 2, 2024, cat. 42.",
    "provenance_text": "Betty Parsons Gallery, New York, by 1950; sold to private collectors, Chicago, 1950; given anonymously to the Art Institute, 1957.",
    "edition": null,
    "publishing_verification_level": "Web Cataloged",
    "internal_department_id": 246,
    "fiscal_year": null,
    "fiscal_year_deaccession": null,
    "is_public_domain": false,
    "is_zoomable": true,
    "max_zoom_window_size": 1280,
    "copyright_notice": "\u00a9 1998 Kate Rothko Prizel & Christopher Rothko / Artists Rights Society (ARS), New York",
    "has_multimedia_resources": false,
    "has_educational_resources": false,
    "has_advanced_imaging": false,
    "colorfulness": 0,
    "color": {
      "h": 341,
      "l": 30,
      "s": 4,
      "percentage": 5.074518320462449e-5,
      "population": 75
    },
    "latitude": null,
    "longitude": null,
    "latlon": null,
    "is_on_view": false,
    "on_loan_display": "<p>On loan to Fondation Louis Vuitton for <i>Mark Rothko</i></p>",
    "gallery_title": null,
    "gallery_id": null,
    "nomisma_id": null,
    "artwork_type_title": "Painting",
    "artwork_type_id": 1,
    "department_title": "Contemporary Art",
    "department_id": "PC-8",
    "artist_id": 36467,
    "artist_title": "Mark Rothko",
    "alt_artist_ids": [],
    "artist_ids": [36467],
    "artist_titles": ["Mark Rothko"],
    "category_ids": ["PC-8"],
    "category_titles": ["Contemporary Art"],
    "term_titles": [
      "painting",
      "rectangles",
      "modern and contemporary art",
      "gray (color)",
      "orange (color)",
      "yellow (color)",
      "colors"
    ],
    "style_id": null,
    "style_title": null,
    "alt_style_ids": [],
    "style_ids": [],
    "style_titles": [],
    "classification_id": "TM-9",
    "classification_title": "painting",
    "alt_classification_ids": ["TM-155"],
    "classification_ids": ["TM-9", "TM-155"],
    "classification_titles": ["painting", "modern and contemporary art"],
    "subject_id": "TM-12656",
    "alt_subject_ids": ["TM-11840", "TM-11905", "TM-11842", "TM-12479"],
    "subject_ids": [
      "TM-12656",
      "TM-11840",
      "TM-11905",
      "TM-11842",
      "TM-12479"
    ],
    "subject_titles": [
      "rectangles",
      "gray (color)",
      "orange (color)",
      "yellow (color)",
      "colors"
    ],
    "material_id": null,
    "alt_material_ids": [],
    "material_ids": [],
    "material_titles": [],
    "technique_id": null,
    "alt_technique_ids": [],
    "technique_ids": [],
    "technique_titles": [],
    "theme_titles": [],
    "image_id": "0a0e16c5-8510-bb2d-b2ca-424feae48d5c",
    "alt_image_ids": [],
    "document_ids": [],
    "sound_ids": [],
    "video_ids": [],
    "text_ids": [],
    "section_ids": [],
    "section_titles": [],
    "site_ids": [],
    "suggest_autocomplete_all": [
      { "input": ["1957.308"], "contexts": { "groupings": ["accession"] } },
      {
        "input": ["Number 19"],
        "weight": 7240,
        "contexts": { "groupings": ["title"] }
      }
    ],
    "source_updated_at": "2024-01-11T00:30:00-06:00",
    "updated_at": "2024-01-11T00:31:49-06:00",
    "timestamp": "2024-01-11T01:46:26-06:00"
  },
  {
    "id": 3816,
    "api_model": "artworks",
    "api_link": "https://api.artic.edu/api/v1/artworks/3816",
    "is_boosted": false,
    "title": "Ornamental Panel With Two Lovers",
    "alt_titles": null,
    "thumbnail": {
      "lqip": "data:image/gif;base64,R0lGODlhBwAFAPQAAGpoVXJxXXRyXXVzXnd2Ynh2YHh3Ynl3Y3l3ZHt5ZHt5ZX17ZXx6Zn17Znx6Z358ZoB+aIF+aYF/aYB/a4J/a4OAaoKAa4OBa4KAbYOBbYWDb4aEb42LdI6Md4+MeAAAACH5BAAAAAAALAAAAAAHAAUAAAUdoBMYVzJo0wFxT9VhzbVZkccUSyM1GQIIBMWBEgIAOw==",
      "width": 3372,
      "height": 2284,
      "alt_text": "A work made of engraving printed in black, on ivory laid paper."
    },
    "main_reference_number": "1956.854",
    "has_not_been_viewed_much": false,
    "boost_rank": null,
    "date_start": 1480,
    "date_end": 1490,
    "date_display": "1480\u201390",
    "date_qualifier_title": "",
    "date_qualifier_id": null,
    "artist_display": "Israhel van Meckenem the Younger\nGerman, c. 1440/45-1503",
    "place_of_origin": "Germany",
    "description": null,
    "short_description": null,
    "dimensions": "16.3 \u00d7 23.9 cm (6 7/16 \u00d7 9 7/16 in.)",
    "dimensions_detail": [
      {
        "depth": null,
        "width": 23,
        "height": 16,
        "diameter": null,
        "clarification": null
      }
    ],
    "medium_display": "Engraving printed in black, on ivory laid paper",
    "inscriptions": null,
    "credit_line": "Bequest of Mrs. Potter Palmer, Jr.",
    "catalogue_display": "<p>Lehrs IX.619</p><p>Bartsch VI.282.205</p><p>Geisberg 471</p><p>Hollstein XXIV.619</p>",
    "publication_history": null,
    "exhibition_history": null,
    "provenance_text": null,
    "edition": null,
    "publishing_verification_level": "Web Basic",
    "internal_department_id": 3,
    "fiscal_year": null,
    "fiscal_year_deaccession": null,
    "is_public_domain": true,
    "is_zoomable": true,
    "max_zoom_window_size": -1,
    "copyright_notice": null,
    "has_multimedia_resources": false,
    "has_educational_resources": false,
    "has_advanced_imaging": false,
    "colorfulness": 12.2228,
    "color": {
      "h": 58,
      "l": 59,
      "s": 12,
      "percentage": 0.22187459099662823,
      "population": 1068
    },
    "latitude": null,
    "longitude": null,
    "latlon": null,
    "is_on_view": false,
    "on_loan_display": "<p>On loan to Chazen Museum of Art in Madison for <i>Art of Enterprise: Israhel van Meckenem's 15th-Century Print Workshop</i></p>",
    "gallery_title": null,
    "gallery_id": null,
    "nomisma_id": null,
    "artwork_type_title": "Print",
    "artwork_type_id": 18,
    "department_title": "Prints and Drawings",
    "department_id": "PC-13",
    "artist_id": 37116,
    "artist_title": "Israhel van Meckenem, the younger",
    "alt_artist_ids": [],
    "artist_ids": [37116],
    "artist_titles": ["Israhel van Meckenem, the younger"],
    "category_ids": ["PC-13"],
    "category_titles": ["Prints and Drawings"],
    "term_titles": [
      "engraving",
      "paper (fiber product)",
      "print",
      "prints and drawing"
    ],
    "style_id": null,
    "style_title": null,
    "alt_style_ids": [],
    "style_ids": [],
    "style_titles": [],
    "classification_id": "TM-12",
    "classification_title": "engraving",
    "alt_classification_ids": ["TM-17", "TM-4"],
    "classification_ids": ["TM-12", "TM-17", "TM-4"],
    "classification_titles": ["engraving", "print", "prints and drawing"],
    "subject_id": null,
    "alt_subject_ids": [],
    "subject_ids": [],
    "subject_titles": [],
    "material_id": "TM-2982",
    "alt_material_ids": [],
    "material_ids": ["TM-2982"],
    "material_titles": ["paper (fiber product)"],
    "technique_id": null,
    "alt_technique_ids": [],
    "technique_ids": [],
    "technique_titles": [],
    "theme_titles": [],
    "image_id": "763257c8-fbf9-0377-54ab-ae3cee7ff7a4",
    "alt_image_ids": [],
    "document_ids": [],
    "sound_ids": [],
    "video_ids": [],
    "text_ids": [],
    "section_ids": [],
    "section_titles": [],
    "site_ids": [],
    "suggest_autocomplete_all": [
      { "input": ["1956.854"], "contexts": { "groupings": ["accession"] } },
      {
        "input": ["Ornamental Panel With Two Lovers"],
        "weight": 843,
        "contexts": { "groupings": ["title"] }
      }
    ],
    "source_updated_at": "2024-01-11T00:30:00-06:00",
    "updated_at": "2024-01-11T00:31:49-06:00",
    "timestamp": "2024-01-11T01:46:26-06:00"
  }]
}
